apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-repo
  links:
  - url: https://quadcorps.atlassian.net/wiki/spaces/QUADCORPS/overview
    title: Architecture Diagrams
    icon: dashboard
  annotations:
    github.com/project-slug: QuadCorps/backstage-demo-entities
    sonarqube.org/project-key: Sample-SQ-project
    grafana/overview-dashboard: "https://grafana.ak.dev.quaddemo.co.uk/d-solo/09ec8aa1e996d6ffcd6817bbaff4db1b/kubernetes-api-server?orgId=1&refresh=10s&from=1699430369643&to=1699433969643&panelId=10"
    jenkins.io/job-full-name: some-project/test-build
    backstage.io/techdocs-ref: url:https://github.com/andrewgkew/doc-test/tree/master
    backstage.io/kubernetes-label-selector: "app.kubernetes.io/name=backstage"
spec:
  type: service
  lifecycle: development
  owner: team-a
  system: artist-engagement-portal
  dependsOn:
    - resource:default/artists-db
  providesApis:
    - artist-api
