apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-repo
  annotations:
    sonarqube.org/project-key: default/Sample-SQ-project
spec:
  type: documentation
  lifecycle: development
  owner: team-a
  system: artist-engagement-portal
  dependsOn:
    - resource:default/artists-db
  providesApis:
    - artist-api
