apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-repo
  annotations:
    sonarqube.org/project-key: default/Sample-SQ-project
    grafana/overview-dashboard: "https://grafana.ak.dev.quaddemo.co.uk/d-solo/09ec8aa1e996d6ffcd6817bbaff4db1b/kubernetes-api-server?orgId=1&refresh=10s&from=1699430369643&to=1699433969643&panelId=10"
spec:
  type: documentation
  lifecycle: development
  owner: team-a
  system: artist-engagement-portal
  dependsOn:
    - resource:default/artists-db
  providesApis:
    - artist-api
