openapi: 3.0.0
info:
  title: Sample API
  version: 1.0.0
paths:
  /user/{userId}:
    get:
      summary: Get user information
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                id: "123"
                name: John Doe
                email: john.doe@example.com
components:
  $ref: definitions.yaml
